Dynatrace/openkit-java

Jenkinsfile
build.gradle
docs/licenses/HEADER.txt
gradle/license.gradle
settings.gradle
src/test/java/com/dynatrace/openkit/core/OpenKitImplTest.java

Adds artifactory publishing. Adds snapshot management. Adds license checks.

Jenkins support

---

src/main/java/com/dynatrace/openkit/core/communication/BeaconSendingContext.java

nextState remembers if a transition to another state was requested.
After the execute method of the current state returns the current state
is updated with the new state.

safer state transition

---

src/main/java/com/dynatrace/openkit/CrashReportingLevel.java
src/main/java/com/dynatrace/openkit/protocol/Beacon.java
src/test/java/com/dynatrace/openkit/OpenKitBuilderTest.java
src/test/java/com/dynatrace/openkit/core/configuration/BeaconConfigurationTest.java
src/test/java/com/dynatrace/openkit/protocol/BeaconTest.java

Differentiate OptIn/OptOut crashes in protocol

---

.travis.yml
build.gradle

During the release of version 1.1, some issues were encountered and fixed directly on the release branch.
This PR contains the cherry-picked commits.

Cherry pick fixes from release branch

---

build.gradle
docs/example.md
src/main/java/com/dynatrace/openkit/api/OpenKitConstants.java

Pump OpenKit Java version to 1.2.0 in the master branch.

Pump versions to 1.2.0

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/protocol/Response.java
src/main/java/com/dynatrace/openkit/protocol/StatusResponse.java
src/main/java/com/dynatrace/openkit/protocol/TimeSyncResponse.java
src/test/java/com/dynatrace/openkit/core/SessionImplTest.java
src/test/java/com/dynatrace/openkit/core/communication/BeaconSendingCaptureOnStateTest.java
src/test/java/com/dynatrace/openkit/core/communication/BeaconSendingContextTest.java
src/test/java/com/dynatrace/openkit/core/communication/BeaconSendingTimeSyncStateTest.java
src/test/java/com/dynatrace/openkit/protocol/BeaconTest.java
src/test/java/com/dynatrace/openkit/protocol/StatusResponseTest.java
src/test/java/com/dynatrace/openkit/protocol/TimeSyncResponseTest.java
src/test/java/com/dynatrace/openkit/test/TestHTTPClient.java

The response returned in OpenKit contains the HTTP response headers

Response contains HTTP response headers

---

CHANGELOG.md
src/main/java/com/dynatrace/openkit/protocol/Beacon.java
src/test/java/com/dynatrace/openkit/protocol/BeaconTest.java

This is now the final PR fixing wrong deviceID issue. It already takes the String deviceID into account.

Wrong device ID was in use for data collection level

---

src/main/java/com/dynatrace/openkit/api/Session.java
src/main/java/com/dynatrace/openkit/core/ActionImpl.java
src/main/java/com/dynatrace/openkit/core/NullSession.java
src/main/java/com/dynatrace/openkit/core/SessionImpl.java
src/main/java/com/dynatrace/openkit/core/WebRequestTracerBaseImpl.java
src/main/java/com/dynatrace/openkit/core/WebRequestTracerStringURL.java
src/main/java/com/dynatrace/openkit/core/WebRequestTracerURLConnection.java
src/main/java/com/dynatrace/openkit/protocol/Beacon.java
src/test/java/com/dynatrace/openkit/core/ActionImplTest.java
src/test/java/com/dynatrace/openkit/core/SessionImplTest.java
src/test/java/com/dynatrace/openkit/core/WebRequestTracerBaseImplTest.java
src/test/java/com/dynatrace/openkit/core/WebRequestTracerStringURLTest.java
src/test/java/com/dynatrace/openkit/core/WebRequestTracerURLConnectionTest.java
src/test/java/com/dynatrace/openkit/protocol/BeaconTest.java

Well not completely standalone, a Session is still required. :)
Also refactored some existing tests, since it was not quite cool the way
it was originally written.

Standalone web request tracing

---

CHANGELOG.md
build.gradle

Pump version to 1.2.0

---

CHANGELOG.md

* Cherry pick from branch release/1.2
* Add latest changes

CHANGELOG updates

---

README.md

This is done for:
* Travis CI
* coveralls.io

Adjust branch names in README

---

CHANGELOG.md
build.gradle

Adjust CHANGELOG and remove SNAPSHOT from version.

Prepare release 1.2.2

---

CHANGELOG.md
version.properties

Adjust CHANGELOG and remove SNAPSHOT from version.

Prepare release 1.3.1

---

build.gradle

Changed loading of the file version.properties file by using Gradle built in file loading mechanism.

Fixed bug related to loading version file

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/providers/HttpURLConnectionWrapper.java
src/test/java/com/dynatrace/openkit/protocol/HTTPClientTest.java

This change introduces an Interface which provide HttpURLConnection wrapper which can be implemented with specific choices. Unit tests were changed to reflect the improvement.

Backport httpclient retry bugfix

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/providers/HttpURLConnectionWrapper.java
src/test/java/com/dynatrace/openkit/protocol/HTTPClientTest.java

This change introduces an Interface which provide a HttpURLConnection wrapper which can be implemented with specific choices. Unit tests were changed to reflect the improvement.

Backport httpclient retry bugfix to 1.3

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/providers/HttpURLConnectionWrapper.java
src/test/java/com/dynatrace/openkit/protocol/HTTPClientTest.java

This change introduces an Interface which provide a HttpURLConnection wrapper which can be implemented with specific choices. Unit tests were changed to reflect the improvement.

Backport httpclient retry bugfix to 1.2

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/providers/HttpURLConnectionWrapper.java
src/test/java/com/dynatrace/openkit/protocol/HTTPClientTest.java

This change introduces an Interface which provide a HttpURLConnection wrapper which can be implemented with specific choices. Unit tests were changed to reflect the improvement.

Backport httpclient retry bugfix to 1.1

---

src/main/java/com/dynatrace/openkit/protocol/HTTPClient.java
src/main/java/com/dynatrace/openkit/providers/HttpURLConnectionWrapper.java

This change introduces an Interface which provide a HttpURLConnection wrapper which can be implemented with specific choices. Unit tests were changed to reflect the improvement.

Backport httpclient retry bugfix to 1.0

---

.travis.yml
build.gradle
gradle/coverage.gradle
gradle/publish.gradle

Additionally improve gradle build

Add deployment to JFrog Bintray

---

src/main/java/com/dynatrace/openkit/core/communication/BeaconSendingInitState.java

Set the "completed flag" after state transition

Minor improvement in init state

---

README.md
src/main/java/com/dynatrace/openkit/AbstractOpenKitBuilder.java

* Remove trailing space in README.md
* Remove unused non-public ctor
* Fix English grammar mistakes

Minor improvements

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle

* Build OpenKit Java with OpenJDK 7 (target compatibility=6)
* Run tests with OpenJDK 6
* Run tests with OpenJDK 7
* Build with Oracle JDK8
* Run tests with Oracle JDK8
* Build with Oracle JDK11
* Run tests with Oracle JDK11

Build OpenKit Java with different JDKs
